spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://super-power-postgres:5432/demo
        username: ${postgres.username}
        password: ${postgres.password}
        