server:
    http:
        port: 8080 # http port
    port: 8443 # https ports using the self signed cert
    ssl:
        key-store: classpath:selfsigned.jks
        key-store-password: password
        key-password: password
